# Generated by Django 4.0.3 on 2022-03-07 21:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('audit_zone', models.CharField(choices=[('Фабрика', 'Фабрика'), ('Склад', 'Склад'), ('Улица', 'Улица')], max_length=200, verbose_name='Зона аудита')),
                ('type_of_risk', models.CharField(choices=[('Падение', 'Падение'), ('Удар', 'Удар'), ('Контузия', 'Контузия')], max_length=200, verbose_name='Оцениваемый риск')),
                ('level_of_risk', models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], max_length=200, verbose_name='Уровень риска')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Аудит',
                'verbose_name_plural': 'Аудиты',
            },
        ),
    ]
